alias ls='ls --color'
alias ll='ls -alF --color'
alias la='ls -A --color'
alias e='emacsclient'
alias em='emacs -nw'

# Source Adds
if [ -d "${HOME}/.env/bashrc.d" ]; then
    for f in $(find "${HOME}/.env/bashrc.d" -type f); do
        source "${f}"
    done
fi

# Local Variables:
# mode: sh
# End:
